# Generated by Django 4.1 on 2022-09-05 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do usuário')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('foto_perfil', models.ImageField(blank=True, upload_to='fotos/', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
