# Generated by Django 4.1 on 2022-09-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tarefas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='colocacao',
            field=models.IntegerField(default=1, verbose_name='Colocação'),
            preserve_default=False,
        ),
    ]
