# Generated by Django 4.1 on 2022-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_colocacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tempo_empresa',
            field=models.CharField(default=1, max_length=100, verbose_name='Tempo de empresa'),
            preserve_default=False,
        ),
    ]
